exp_name: "snapshot_f4c"

random_bgcolor: true
bgcolor: [255., 255., 255.]
img_size: [540, 540]

pose:
  lr: 0.001
  decay: 100
  iters: 300

dataset:
  train:
    dataset_path: "data/snapshot/f4c_train"
    batch_size: 1
    num_workers: 1

    maxframes: -1

  test_view:
    dataset_path: "data/snapshot/f4c_test"
    name: 'snapshot'
    skip: 1
    maxframes: -1
    batch_size: 1
    num_workers: 1

  test_freeview:
    dataset_path: "data/snapshot/f4c_test"
    batch_size: 1
    num_workers: 1
    src_type: 'wild'

model:
  img_size: [540, 540]

  subdivide_iters: [10001]

  appearance:
    face_color: true
    color_init: 0.5

  canonical_geometry:
    radius_scale: 1.0
    deform_scale: true
    deform_so3: true

    sigma: 0.001

  renderer:
    name: 'gaussian'

  non_rigid:
    name: 'basic'
    condition_code_size: 69
    mlp_width: 128
    mlp_depth: 6
    skips: [ 4 ]
    multires: 6       # log2 of max freq for positional encoding (3D location)
    i_embed: 0        # set 0 for default positional encoding, -1 for none
    kick_in_iter: 100000
    full_band_iter: 150000

  normal_renderer:
    name: 'mesh'
    soft_mask: true
    sigma: 0.00001

  shadow_module:
    name: 'basic'
    type: 1
    condition_code_size: 162
    mlp_width: 128
    mlp_depth: 3
    skips: [ 4 ]
    multires: 6       # log2 of max freq for positional encoding (3D location)
    i_embed: 0        # set 0 for default positional encoding, -1 for none

train:
  losses:
    laplacian:
      coeff_observation: 10.0

    normal:
      mask_dilate: true
      kernel_size: 7
      coeff_mask: 1.0
      coeff_consist: 0.10

    color_consist:
      coeff: 0.050

  lr:
    appearance: 0.0005
    canonical_geometry: 0.0005
    canonical_geometry_xyz: 0.0005
    shadow: 0.0005

  lr_update_exp: true
  lr_decay_steps: 100000

  log_freq: 10
  tb_freq: 10000
  eval_freq: 10000
  save_freq: 10000
  total_iters: 200000